### ISSUE TITLE
shield blocks unblockable types of damage

### ISSUE THREAD

**Issue by majijn** [TheCallunxz/Shadowrite#12]
I had a wither loose in a test world and it started targetting the warriors, that how I found out that they dont seem to be considered undead 

then , after they killed the wither (i spawned more warriors, lmao)
some of the survivors with shields just keep holding their shied up, and it was stopping the wither effect from damaging them. they're stuck doing that now, and they keep on blocking all types of damage, including a discidia ritual from astral sorcery

I'm guessing they also block poison damage however i didnt test that.

**Comment by TheCallunxz** [comment]
I have no idea how you're bug reporting so much but thanks lol. When I have time I'll make a big fix patch!

**Comment by majijn** [comment]
the bugs are just showing up!
to be fair part of it may be that ive  had to make my modlist even smaller than it had been before because ive got to use an old system for the moment,
 so I'm getting more shadow warrior spawns 
which means im interacting more with your lil guys, love the mod btw!

**Comment by majijn** [comment]
![2019-03-12_00 27 55](https://user-images.githubusercontent.com/18368034/54167411-d65a2e80-4469-11e9-8098-fcfec0c25229.png)
![2019-03-12_00 30 04](https://user-images.githubusercontent.com/18368034/54167412-d65a2e80-4469-11e9-9e94-78f84240d063.png)
![2019-03-12_00 31 53](https://user-images.githubusercontent.com/18368034/54167413-d65a2e80-4469-11e9-99e3-5593fc9060c4.png)
fighting back the wither (which is fun)
n two pics of the dude that got stuck shieding  while withered and then after the wither effect ran off
in the last pic they're in the range of a discidia ritual which was 3 shotting withers, they're just tanking it with their shields

**Comment by majijn** [comment]
reloading the world causes them to stop holding their shields up (they died immediately to the ritual)

I caused another one to hold his shield up, and yes, he can survive being dropped into the void (the noise it makes is horrendous lmao)
