### ISSUE TITLE
inability to crit while shadow feather is being used

### ISSUE THREAD

**Issue by majijn** [TheCallunxz/Shadowrite#6]
it's really messing up with my TTK the shadow warriors that I cant crit them, especially the diamond-clad ones.

**Comment by TheCallunxz** [comment]
Hey, thanks for bug reporting. If I have time I'll try and fix these bugs but very busy currently :/

**Comment by majijn** [comment]
glad to hear its just you being busy and nothing too bad! hope things go easy on you!

**Comment by majijn** [comment]
also every now and again the feather stops working momentarily, a moment so short im not sure if its me not pressing the shift key properly. but it only seems to happen when loading/unloading chunks (as im playing on a potato now unfortunately =( )

**Comment by majijn** [comment]
im still having these happen

**Comment by TheCallunxz** [comment]
You can't crit while the shadow feather is in the hotbar? That is odd, it should be working now. I'll look into it again.
